### ISSUE TITLE
Update pypi.org version

### ISSUE THREAD

**Issue by danieluisilva** [jckw/django-bootstrap-daterangepicker#21]
Hi, 

It's possible to update pypi version to 1.0.6?

I'm using Django 3 and have a error on importing six.

Ty

**Comment by jckw** [comment]
Whoops, forgot to publish it! Should be up now: https://pypi.org/project/django-bootstrap-daterangepicker/1.0.6/

On 6 May 2020, at 18:17, danieluisilva <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,

It's possible to update pypi version to 1.0.6?

I'm using Django 3 and have a error on importing six.

Ty
