### ISSUE TITLE
force_text is deprecated as of Django 3.0, will be removed in 4.0

### ISSUE THREAD

**Issue by dfrank-a** [jckw/django-bootstrap-daterangepicker#23]
Seeing the following warning when running tests in my project: 

```
RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
    unicode_value = force_text(value, strings_only=True)
```

**Comment by jckw** [comment]
ah nice spot! Mind submitting a PR to update it to whatever the replacement is?

**Comment by jckw** [comment]
Fixed in https://pypi.org/project/django-bootstrap-daterangepicker/1.1.0/
