### ISSUE TITLE
 django.utils.translation import string_concat is deprecated in django>= 1.11

### ISSUE THREAD

**Issue by phithor** [jckw/django-bootstrap-daterangepicker#6]
Hi, this module does not work with newer django versions. Are you planning to update it to support newer versions? Thanks.

**Comment by jckw** [comment]
What's the replacement/equivalent for `string_concat`?

I'll happily update the package!

**Comment by phithor** [comment]
Thanks!

format_lazy() should be used instead:
https://stackoverflow.com/questions/29252312/how-can-i-join-lazy-translation-in-django
